-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 10:30:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inventory` DEFAULT CHARACTER SET utf8 ;
USE `Inventory` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory`.`client` (
  `idClient` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surnames` VARCHAR(45) NOT NULL,
  `identificationCard` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  UNIQUE INDEX `idCliente_UNIQUE` (`idClient` ASC),
  UNIQUE INDEX `cedula_UNIQUE` (`identificationCard` ASC),
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory`.`person` (
  `idPerson` INT NOT NULL,
  `identificationCard` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surnames` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `identificationCard_UNIQUE` (`identificationCard` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory`.`sale` (
  `idSale` INT NOT NULL,
  `saleDate` DATE NULL,
  `totalValue` DOUBLE NULL,
  `client_idClient` INT NOT NULL,
  `person_idPerson` INT NOT NULL,
  UNIQUE INDEX `idventa_UNIQUE` (`idSale` ASC),
  PRIMARY KEY (`idSale`, `client_idClient`, `person_idPerson`),
  INDEX `fk_sale_client1_idx` (`client_idClient` ASC),
  INDEX `fk_sale_person1_idx` (`person_idPerson` ASC),
  CONSTRAINT `fk_sale_client1`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `mydb`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_person1`
    FOREIGN KEY (`person_idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory`.`laboratory` (
  `idlaboratory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idlaboratory`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory`.`medicine` (
  `idMedicine` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `expirationDate` DATE NOT NULL,
  `quantity` INT NOT NULL,
  `fabricationDate` DATE NOT NULL,
  `price` DOUBLE NOT NULL,
  `laboratory_idlaboratory` INT NOT NULL,
  `person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idMedicine`, `laboratory_idlaboratory`, `person_idPerson`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC),
  INDEX `fk_medicine_laboratory_idx` (`laboratory_idlaboratory` ASC),
  INDEX `fk_medicine_person1_idx` (`person_idPerson` ASC),
  CONSTRAINT `fk_medicine_laboratory`
    FOREIGN KEY (`laboratory_idlaboratory`)
    REFERENCES `mydb`.`laboratory` (`idlaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_person1`
    FOREIGN KEY (`person_idPerson`)
    REFERENCES `mydb`.`person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory`.`sale detail` (
  `idSaleDetail` INT NOT NULL,
  `cuantity` INT NOT NULL,
  `medicine_idMedicine` INT NOT NULL,
  `sale_idSale` INT NOT NULL,
  PRIMARY KEY (`idSaleDetail`, `medicine_idMedicine`, `sale_idSale`),
  UNIQUE INDEX `iddetalleVenta_UNIQUE` (`idSaleDetail` ASC),
  INDEX `fk_sale detail_medicine1_idx` (`medicine_idMedicine` ASC),
  INDEX `fk_sale detail_sale1_idx` (`sale_idSale` ASC),
  CONSTRAINT `fk_sale detail_medicine1`
    FOREIGN KEY (`medicine_idMedicine`)
    REFERENCES `mydb`.`medicine` (`idMedicine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale detail_sale1`
    FOREIGN KEY (`sale_idSale`)
    REFERENCES `mydb`.`sale` (`idSale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
